app_id: document_search.app
display_name: Document Search
publisher_name: Document Search
create_desktop_icon: true
launch_at_startup: false
setup_icon_file: windows/runner/resources/app_icon.ico
locales:
  - en
